// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oabpwlumbydradjyfaml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hYnB3bHVtYnlkcmFkanlmYW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDYxMDgsImV4cCI6MjA2NzY4MjEwOH0.kWVsM1H0pNXNL54ZmWvnNfAooQuGoIne-Ztp1dq7hsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});